/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif 
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



#include <stdlib.h>
#include <string.h>
#include "AS3/AS3.h"
#define swig_as3(X) inline_as3("import com.adobe.flascc.swig.*; " X)


/* Contract support */

#define SWIG_contract_assert(expr, msg) if (!(expr)) {int msglen = strlen(msg);__asm__ volatile ("throw new Exception(CModule.readString(%0, %1))": : "r"(msg), "r"(msglen));}



#include <string.h>
#include "flash3dlib.h"

__attribute__((annotate("as3sig:public function _wrap_MAX_JOINTS():int")))
void _wrap_MAX_JOINTS() {
  int result ;
  
  result = 255;
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_JOINT_POSE_LEN():int")))
void _wrap_JOINT_POSE_LEN() {
  int result ;
  
  result = 4*7;
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_JOINT_BIND_LEN():int")))
void _wrap_JOINT_BIND_LEN() {
  int result ;
  
  result = 4*12;
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_WORLD_MATRICES_LEN():int")))
void _wrap_WORLD_MATRICES_LEN() {
  int result ;
  
  result = 4*12;
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_BLEND_WEIGHTS():Number")))
void _wrap_BLEND_WEIGHTS() {
  double result ;
  
  result = 0.8;
  {
    AS3_DeclareVar(asresult, Number);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_PARTICLE_JOINT_LEN():int")))
void _wrap_PARTICLE_JOINT_LEN() {
  int result ;
  
  result = 4*5+1;
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_MAX_JOINT_PARTICLES():int")))
void _wrap_MAX_JOINT_PARTICLES() {
  int result ;
  
  result = 255;
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_VEC3_LEN():int")))
void _wrap_VEC3_LEN() {
  int result ;
  
  result = 4*3;
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_MATRIX_LEN():int")))
void _wrap_MATRIX_LEN() {
  int result ;
  
  result = 4*16;
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_BIND_PARAM_LEN():int")))
void _wrap_BIND_PARAM_LEN() {
  int result ;
  
  result = 4*20;
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_BIND_RESULT_LEN():int")))
void _wrap_BIND_RESULT_LEN() {
  int result ;
  
  result = 4*16;
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_BIND_COUNT_MAX():int")))
void _wrap_BIND_COUNT_MAX() {
  int result ;
  
  result = 20;
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_examineBytes(buffer:int, bufferSize:int):int")))
void _wrap_examineBytes() {
  unsigned char *arg1 = (unsigned char *) 0 ;
  int arg2 ;
  int result ;
  
  {
    AS3_GetScalarFromVar(arg1, buffer);
  }
  {
    AS3_GetScalarFromVar(arg2, bufferSize);
  }
  result = (int)examineBytes((unsigned char const *)arg1,arg2);
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_poseLocalToWorld(localPose:int, worldPose:int, parentIndices:int, numJoints:int):void")))
void _wrap_poseLocalToWorld() {
  unsigned char *arg1 = (unsigned char *) 0 ;
  unsigned char *arg2 = (unsigned char *) 0 ;
  unsigned char *arg3 = (unsigned char *) 0 ;
  unsigned int arg4 ;
  
  {
    AS3_GetScalarFromVar(arg1, localPose);
  }
  {
    AS3_GetScalarFromVar(arg2, worldPose);
  }
  {
    AS3_GetScalarFromVar(arg3, parentIndices);
  }
  {
    AS3_GetScalarFromVar(arg4, numJoints);
  }
  poseLocalToWorld((unsigned char const *)arg1,(unsigned char const *)arg2,(unsigned char const *)arg3,arg4);
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_updateGlobalProperties(worldPose:int, inverseBindPose:int, globalMatrices:int, numJoints:int, useDualQuat:int):void")))
void _wrap_updateGlobalProperties() {
  unsigned char *arg1 = (unsigned char *) 0 ;
  unsigned char *arg2 = (unsigned char *) 0 ;
  unsigned char *arg3 = (unsigned char *) 0 ;
  unsigned int arg4 ;
  Boolean arg5 ;
  
  {
    AS3_GetScalarFromVar(arg1, worldPose);
  }
  {
    AS3_GetScalarFromVar(arg2, inverseBindPose);
  }
  {
    AS3_GetScalarFromVar(arg3, globalMatrices);
  }
  {
    AS3_GetScalarFromVar(arg4, numJoints);
  }
  {
    AS3_GetScalarFromVar(arg5, useDualQuat);
  }
  updateGlobalProperties((unsigned char const *)arg1,(unsigned char const *)arg2,arg3,arg4,arg5);
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_differencePose(currentPose:int, nextPose:int, targetPose:int, numJoints:int, blendWeight:Number, highQuality:int):void")))
void _wrap_differencePose() {
  unsigned char *arg1 = (unsigned char *) 0 ;
  unsigned char *arg2 = (unsigned char *) 0 ;
  unsigned char *arg3 = (unsigned char *) 0 ;
  unsigned int arg4 ;
  float arg5 ;
  Boolean arg6 ;
  
  {
    AS3_GetScalarFromVar(arg1, currentPose);
  }
  {
    AS3_GetScalarFromVar(arg2, nextPose);
  }
  {
    AS3_GetScalarFromVar(arg3, targetPose);
  }
  {
    AS3_GetScalarFromVar(arg4, numJoints);
  }
  {
    AS3_GetScalarFromVar(arg5, blendWeight);
  }
  {
    AS3_GetScalarFromVar(arg6, highQuality);
  }
  differencePose((unsigned char const *)arg1,(unsigned char const *)arg2,(unsigned char const *)arg3,arg4,arg5,arg6);
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_slerpPose(currentPose:int, nextPose:int, targetPose:int, numJoints:int, blendWeight:Number, highQuality:int):void")))
void _wrap_slerpPose() {
  unsigned char *arg1 = (unsigned char *) 0 ;
  unsigned char *arg2 = (unsigned char *) 0 ;
  unsigned char *arg3 = (unsigned char *) 0 ;
  unsigned int arg4 ;
  float arg5 ;
  Boolean arg6 ;
  
  {
    AS3_GetScalarFromVar(arg1, currentPose);
  }
  {
    AS3_GetScalarFromVar(arg2, nextPose);
  }
  {
    AS3_GetScalarFromVar(arg3, targetPose);
  }
  {
    AS3_GetScalarFromVar(arg4, numJoints);
  }
  {
    AS3_GetScalarFromVar(arg5, blendWeight);
  }
  {
    AS3_GetScalarFromVar(arg6, highQuality);
  }
  slerpPose((unsigned char const *)arg1,(unsigned char const *)arg2,(unsigned char const *)arg3,arg4,arg5,arg6);
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_transformVector(jointPose:int, position:int, target:int):void")))
void _wrap_transformVector() {
  unsigned char *arg1 = (unsigned char *) 0 ;
  float *arg2 ;
  float *arg3 ;
  
  {
    AS3_GetScalarFromVar(arg1, jointPose);
  }
  {
    AS3_GetScalarFromVar(arg2, position);
  }
  {
    AS3_GetScalarFromVar(arg3, target);
  }
  transformVector((unsigned char const *)arg1,arg2,arg3);
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_jointPoseToMatrix(jointPose:int, mat:int):void")))
void _wrap_jointPoseToMatrix() {
  unsigned char *arg1 = (unsigned char *) 0 ;
  float *arg2 ;
  
  {
    AS3_GetScalarFromVar(arg1, jointPose);
  }
  {
    AS3_GetScalarFromVar(arg2, mat);
  }
  jointPoseToMatrix((unsigned char const *)arg1,arg2);
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_transformVectors(pose:int, particleJoints:int, numParticles:int, dv:int):void")))
void _wrap_transformVectors() {
  unsigned char *arg1 = (unsigned char *) 0 ;
  unsigned char *arg2 = (unsigned char *) 0 ;
  unsigned int arg3 ;
  unsigned char *arg4 = (unsigned char *) 0 ;
  
  {
    AS3_GetScalarFromVar(arg1, pose);
  }
  {
    AS3_GetScalarFromVar(arg2, particleJoints);
  }
  {
    AS3_GetScalarFromVar(arg3, numParticles);
  }
  {
    AS3_GetScalarFromVar(arg4, dv);
  }
  transformVectors((unsigned char const *)arg1,(unsigned char const *)arg2,arg3,arg4);
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_generateDifferencePose(sourcePose:int, reference:int, differencePose:int, numJoints:int):void")))
void _wrap_generateDifferencePose() {
  unsigned char *arg1 = (unsigned char *) 0 ;
  unsigned char *arg2 = (unsigned char *) 0 ;
  unsigned char *arg3 = (unsigned char *) 0 ;
  unsigned int arg4 ;
  
  {
    AS3_GetScalarFromVar(arg1, sourcePose);
  }
  {
    AS3_GetScalarFromVar(arg2, reference);
  }
  {
    AS3_GetScalarFromVar(arg3, differencePose);
  }
  {
    AS3_GetScalarFromVar(arg4, numJoints);
  }
  generateDifferencePose((unsigned char const *)arg1,(unsigned char const *)arg2,(unsigned char const *)arg3,arg4);
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_updateJointsBindInfo(pose:int, bindParams:int, bindResults:int, bindCount:int):void")))
void _wrap_updateJointsBindInfo() {
  unsigned char *arg1 = (unsigned char *) 0 ;
  unsigned char *arg2 = (unsigned char *) 0 ;
  unsigned char *arg3 = (unsigned char *) 0 ;
  unsigned int arg4 ;
  
  {
    AS3_GetScalarFromVar(arg1, pose);
  }
  {
    AS3_GetScalarFromVar(arg2, bindParams);
  }
  {
    AS3_GetScalarFromVar(arg3, bindResults);
  }
  {
    AS3_GetScalarFromVar(arg4, bindCount);
  }
  updateJointsBindInfo((unsigned char const *)arg1,(unsigned char const *)arg2,arg3,arg4);
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_getParticleJointSize():int")))
void _wrap_getParticleJointSize() {
  int result ;
  
  result = (int)getParticleJointSize();
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_updatePoseMatricesAndSkinDatas(jointPoseMatrices:int, jointSkinDatas:int, animationPoses:int, parentIndices:int, inverseBindPose:int, frame:int, numJoints:int, useDualQuat:int):void")))
void _wrap_updatePoseMatricesAndSkinDatas() {
  unsigned char *arg1 = (unsigned char *) 0 ;
  unsigned char *arg2 = (unsigned char *) 0 ;
  unsigned char *arg3 = (unsigned char *) 0 ;
  unsigned char *arg4 = (unsigned char *) 0 ;
  unsigned char *arg5 = (unsigned char *) 0 ;
  unsigned int arg6 ;
  unsigned int arg7 ;
  Boolean arg8 ;
  
  {
    AS3_GetScalarFromVar(arg1, jointPoseMatrices);
  }
  {
    AS3_GetScalarFromVar(arg2, jointSkinDatas);
  }
  {
    AS3_GetScalarFromVar(arg3, animationPoses);
  }
  {
    AS3_GetScalarFromVar(arg4, parentIndices);
  }
  {
    AS3_GetScalarFromVar(arg5, inverseBindPose);
  }
  {
    AS3_GetScalarFromVar(arg6, frame);
  }
  {
    AS3_GetScalarFromVar(arg7, numJoints);
  }
  {
    AS3_GetScalarFromVar(arg8, useDualQuat);
  }
  updatePoseMatricesAndSkinDatas(arg1,arg2,(unsigned char const *)arg3,(unsigned char const *)arg4,(unsigned char const *)arg5,arg6,arg7,arg8);
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_getCondensedSkinDatas(condensedSkinDatas:int, jointSkinDatas:int, jointsMap:int, numJointsMap:int, useDualQuat:int):void")))
void _wrap_getCondensedSkinDatas() {
  unsigned char *arg1 = (unsigned char *) 0 ;
  unsigned char *arg2 = (unsigned char *) 0 ;
  unsigned char *arg3 = (unsigned char *) 0 ;
  unsigned int arg4 ;
  Boolean arg5 ;
  
  {
    AS3_GetScalarFromVar(arg1, condensedSkinDatas);
  }
  {
    AS3_GetScalarFromVar(arg2, jointSkinDatas);
  }
  {
    AS3_GetScalarFromVar(arg3, jointsMap);
  }
  {
    AS3_GetScalarFromVar(arg4, numJointsMap);
  }
  {
    AS3_GetScalarFromVar(arg5, useDualQuat);
  }
  getCondensedSkinDatas(arg1,(unsigned char const *)arg2,(unsigned char const *)arg3,arg4,arg5);
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_getCondensedPoseMatrices(condensedPoseMatrices:int, jointPoseMatrices:int, jointsMap:int, numJointsMap:int):void")))
void _wrap_getCondensedPoseMatrices() {
  unsigned char *arg1 = (unsigned char *) 0 ;
  unsigned char *arg2 = (unsigned char *) 0 ;
  unsigned char *arg3 = (unsigned char *) 0 ;
  unsigned int arg4 ;
  
  {
    AS3_GetScalarFromVar(arg1, condensedPoseMatrices);
  }
  {
    AS3_GetScalarFromVar(arg2, jointPoseMatrices);
  }
  {
    AS3_GetScalarFromVar(arg3, jointsMap);
  }
  {
    AS3_GetScalarFromVar(arg4, numJointsMap);
  }
  getCondensedPoseMatrices(arg1,(unsigned char const *)arg2,(unsigned char const *)arg3,arg4);
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_copyFrame(dst_matrices:int, dst_poses:int, src_matrices:int, src_poses:int, matricesLen:int, posesLen:int):void")))
void _wrap_copyFrame() {
  unsigned char *arg1 = (unsigned char *) 0 ;
  unsigned char *arg2 = (unsigned char *) 0 ;
  unsigned char *arg3 = (unsigned char *) 0 ;
  unsigned char *arg4 = (unsigned char *) 0 ;
  unsigned int arg5 ;
  unsigned int arg6 ;
  
  {
    AS3_GetScalarFromVar(arg1, dst_matrices);
  }
  {
    AS3_GetScalarFromVar(arg2, dst_poses);
  }
  {
    AS3_GetScalarFromVar(arg3, src_matrices);
  }
  {
    AS3_GetScalarFromVar(arg4, src_poses);
  }
  {
    AS3_GetScalarFromVar(arg5, matricesLen);
  }
  {
    AS3_GetScalarFromVar(arg6, posesLen);
  }
  copyFrame(arg1,arg2,arg3,arg4,arg5,arg6);
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


